/**
 * M3-01 验证入口：前端骨架、类型绑定（T14）与 EventStore（设计 D7/D8/T14）。
 *
 * 覆盖 DoD：
 *   1) 生成物一致性：重新生成 `packages/protocol/src/bindings.ts` 并
 *      `git diff --exit-code`（T14；`scripts/ci/bindings.mjs check`）；
 *   2) EventStore：去重 / 乱序排序 / `last_seq` 补读 / 缺口 >10k 提示与
 *      清缓存重载最近 N 条（默认 500，可配置）/ 16ms 批处理（单测 + 集成）；
 *   3) 压力：10 会话 × 50 delta/s 无重复渲染；`gap=true` 可补齐（集成）；
 *   4) 慢消费注入：桥接消费者阻塞不反压提交/健康/读取（Rust 集成）；
 *      配套核心侧 reader 心跳证据（复用 M2-04 DoD3 慢订阅者用例）。
 *
 * 用法：node scripts/test/m3-01/verify-m3-01.mjs
 * 环境：Cargo 经 scripts/test/lib/exec.mjs 解析；T14 校验要求生成物已入库
 *       （CI 在提交后执行；本地先 `git add packages/protocol/src/bindings.ts`）。
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";

import { bin, pnpmCommand, repoRoot, run, summarize } from "../lib/exec.mjs";

const checks = [];
const record = (name, exit, expect = 0) => checks.push({ name, exit, expect });
const cargo = bin("cargo");
const node = process.execPath;
const { command: pnpm, prefix: pnpmPrefix } = pnpmCommand();
const pnpmRun = (list, options) => run(pnpm, [...pnpmPrefix, ...list], options);

const BINDINGS = path.join(repoRoot, "packages", "protocol", "src", "bindings.ts");
const BINDINGS_RELATIVE = path.relative(repoRoot, BINDINGS).split(path.sep).join("/");

// ===== DoD1：T14 生成物一致性（重新生成 + git diff --exit-code） =====

record(
  "T14 bindings：重新生成 + git diff --exit-code（scripts/ci/bindings.mjs check）",
  run(node, [path.join(repoRoot, "scripts", "ci", "bindings.mjs"), "check"]),
);

record(
  "bindings 生成物必须被 git 跟踪（AGENTS §2.8）",
  run("git", ["ls-files", "--error-unmatch", BINDINGS_RELATIVE]),
);

// ===== DoD1：生成物内容静态断言（D7 命令全集 = 25；ADR-006 四命令 + health） =====

{
  const problems = [];
  let text = "";
  try {
    text = readFileSync(BINDINGS, "utf8");
  } catch (error) {
    problems.push(`读取失败：${error.message}`);
  }
  if (!text.includes("generated by Tauri Specta")) {
    problems.push("缺少 Tauri Specta 生成头（禁止手改标记）");
  }
  const commands = [
    "runtimes_list",
    "session_list",
    "session_create",
    "session_send",
    "session_interrupt",
    "session_dispose",
    "messages_page",
    "permissions_pending",
    "permission_resolve",
    "settings_get",
    "settings_set",
    "backup_create",
    "backup_list",
    "backup_restore",
    "app_restart",
    "run_retry",
    "runtime_retry",
    "runtime_enable",
    "workspace_set",
    "export_diagnostics",
    "health",
    "startup_get",
    "startup_pick_target",
    "startup_migrate",
    "app_exit",
  ];
  for (const command of commands) {
    if (!text.includes(`__TAURI_INVOKE("${command}"`)) {
      problems.push(`命令缺失：${command}`);
    }
  }
  if (!text.includes('makeEvent<AetherEvent>("aether://event")')) {
    problems.push("事件通道缺失：aether://event");
  }
  if (problems.length > 0) {
    console.error("[verify-m3-01] bindings 内容断言失败：");
    for (const problem of problems) {
      console.error(`  - ${problem}`);
    }
  }
  record(
    `bindings 内容：D7 全集 ${commands.length} 命令 + aether://event 事件`,
    problems.length === 0 ? 0 : 1,
  );
}

// ===== DoD2/DoD3：EventStore 单测 + 集成（含 10×50 压力与 gap 补齐） =====

record(
  "pnpm --filter @aether/desktop test（EventStore 去重/乱序/补读/>10k/16ms 批处理/压力/缺口补齐）",
  pnpmRun(["--filter", "@aether/desktop", "test"]),
);

// ===== DoD4：事件桥慢消费不反压（Rust 集成） =====

record(
  "m3_01_event_bridge（转发/信封等价/慢消费不反压+Lagged 计数/spawn_app 冒烟；--nocapture）",
  run(cargo, [
    "test",
    "-p",
    "aether-tauri",
    "--test",
    "m3_01_event_bridge",
    "--",
    "--nocapture",
  ]),
);

record(
  "m2_04_backpressure dod3（核心侧慢订阅者不阻塞 reader/health/interrupt：DoD4 的 reader 心跳证据链）",
  run(cargo, [
    "test",
    "-p",
    "aether-control",
    "--test",
    "m2_04_backpressure",
    "dod3",
    "--",
    "--nocapture",
  ]),
);

// ===== 回归：命令面契约不变（M1-08 校验矩阵 + health 契约） =====

record(
  "aether-tauri ipc_validation + health_command 回归（命令面/严格校验契约不变）",
  run(cargo, [
    "test",
    "-p",
    "aether-tauri",
    "--test",
    "ipc_validation",
    "--test",
    "health_command",
  ]),
);

process.exit(summarize("verify-m3-01", checks));
