// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	runtimesList: () => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("runtimes_list")),
	sessionList: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("session_list", { payload })),
	sessionCreate: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("session_create", { payload })),
	sessionSend: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("session_send", { payload })),
	sessionInterrupt: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("session_interrupt", { payload })),
	sessionDispose: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("session_dispose", { payload })),
	messagesPage: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("messages_page", { payload })),
	permissionsPending: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("permissions_pending", { payload })),
	permissionResolve: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("permission_resolve", { payload })),
	settingsGet: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("settings_get", { payload })),
	settingsSet: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("settings_set", { payload })),
	backupCreate: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("backup_create", { payload })),
	/**  ADR-004：无参数命令；缺省载荷等价空对象，任何成员都会被严格模式拒绝。 */
	backupList: (payload: unknown | null) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("backup_list", { payload })),
	/**  ADR-004/D13：外部候选先 canonicalize（存在性 + `.db` 后缀）再进入恢复七步。 */
	backupRestore: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("backup_restore", { payload })),
	/**  ADR-004：显式 `confirm:true` 才可重启（复用 D2 关闭序列）。 */
	appRestart: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("app_restart", { payload })),
	/**  ADR-004/M3-06：仅终态 run 可重试（`run_id` ULID；状态由后端判定）。 */
	runRetry: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("run_retry", { payload })),
	/**  ADR-004/M1-10：仅 `disabled + start_failed` 可用（白名单与状态由后端判定）。 */
	runtimeRetry: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("runtime_retry", { payload })),
	/**  ADR-004/M1-10：仅 `disabled` 可用；`untrusted`/`version_mismatch` 需先修复。 */
	runtimeEnable: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("runtime_enable", { payload })),
	/**  ADR-004/D14：`workspace_id` 或 `root_path`（canonicalize + 同步盘拒绝）。 */
	workspaceSet: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("workspace_set", { payload })),
	exportDiagnostics: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("export_diagnostics", { payload })),
	/**
	 *  ADR-007 决策 1：核心健康查询（无参数；严格解析拒绝未知成员）。
	 * 
	 *  返回 `HealthReport`（`storage_state` / `write_queue_depth` / `runtimes` 摘要 / `ts`）；
	 *  仅本地 IPC，不落库、不产生事件。UI 每 5s 轮询，15s 无响应显示「核心未响应」+ 重启入口。
	 *  数据源：`EventPipeline::health()` + 监督器摘要（M2-07 接线）。
	 * 
	 *  说明（M2-07）：命令为 async——E2E 探针经 `AETHER_E2E_HEALTH_STALL_MS` 在运行时上
	 *  挂起本命令（模拟无响应；不阻塞主线程），生产路径无等待。
	 */
	health: (payload: unknown | null) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("health", { payload })),
	/**
	 *  M1-06：启动门快照（拒绝启动时仍可达；UI 据此渲染门界面）。
	 *  ADR-006：无参数命令；缺省载荷等价空对象，任何成员都会被严格模式拒绝。
	 */
	startupGet: (payload: unknown | null) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("startup_get", { payload })),
	/**
	 *  M1-06：迁移目标目录选择（`DirectoryPicker` 抽象：生产为系统对话框，测试/E2E 注入替身；
	 *  不新增 WebView capability 权限面）。用户取消返回 `{ "target_dir": null }`。
	 *  ADR-006：无参数命令；缺省载荷等价空对象，任何成员都会被严格模式拒绝。
	 */
	startupPickTarget: (payload: unknown | null) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("startup_pick_target", { payload })),
	/**  M1-06/A4：执行迁移（复制 → sha256 校验 → 原子替换 → 指针锁定新目录）。 */
	startupMigrate: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("startup_migrate", { payload })),
	/**
	 *  M1-06：退出应用（拒绝启动界面「退出」按钮；不暴露窗口控制能力）。
	 *  ADR-006（v0.3 对齐）：`{ confirm: true }` 显式确认；严格解析拒绝未知成员。
	 */
	appExit: (payload: unknown) => typedError<unknown, IpcError_Serialize>(__TAURI_INVOKE("app_exit", { payload })),
};

/** Events */
export const events = {
	aetherEvent: makeEvent<AetherEvent>("aether://event"),
};

/* Types */
/**
 *  `aether://event` 事件载荷：与 `aether_core::EventEnvelope` 的 JSON 形状一致
 *  （9 字段：`v/id/session_id/run_id/runtime_id/seq/ts/type/payload`）。
 * 
 *  等价性由 `tests/event_bridge.rs` 的序列化对照断言锁定（字段增删必须同版本完成）。
 */
export type AetherEvent = {
	v: number,
	id: string,
	session_id: string,
	run_id: string | null,
	runtime_id: string,
	seq: number,
	ts: number,
	type: string,
	payload: unknown,
};

/**
 *  `app_exit`（ADR-006 决策 1，v0.3 对齐）：拒绝启动页退出；显式 `confirm:true`
 *  才允许退出（与 `app_restart` 的 confirm 约定一致）。
 */
export type AppExitRequest = {
	confirm: boolean,
};

/**  `app_restart`（ADR-004）：显式 `confirm:true` 才允许复用关闭序列重启。 */
export type AppRestartRequest = {
	confirm: boolean,
};

export type BackupCreateRequest = {
	label?: string | null,
};

/**  `backup_list`（ADR-004）：无参数命令；非空成员一律拒绝。 */
export type BackupListRequest = Record<string, never>;

export type BackupRestoreRequest = {
	source: BackupSource,
};

/**  备份来源（ADR-004 `backup_restore`）：内部备份 id 枚举 或 外部 `.db` 路径。 */
export type BackupSource = 
/**  内部备份 id（`backups` 表白名单，仅 ULID 格式层校验；存在性由后端判定）。 */
({ internal: {
	id: string,
} }) & { external?: never } | 
/**  外部 `.db` 路径（canonicalize + 存在性 + 后缀，D13 七步第一步）。 */
({ external: {
	path: string,
} }) & { internal?: never };

export type ExportDiagnosticsRequest = {
	target_dir: string,
};

/**
 *  `health`（ADR-007 决策 1）：无参数命令（严格解析：任何成员拒绝）。
 * 
 *  仅本地 IPC 查询：不落库、不产生事件；返回 `HealthReport`
 *  （`storage_state` / `write_queue_depth` / `runtimes` 摘要 / `ts`）。
 */
export type HealthRequest = Record<string, never>;

/**  IPC 命令错误的线上形态：`{ "code": "...", "message": "...", "field": "..." }`。 */
export type IpcError = IpcError_Serialize | IpcError_Deserialize;

/**  结构化错误码（稳定枚举，新增取值需走设计变更评审）。 */
export type IpcErrorCode = 
/**  请求体不是 JSON 对象，或 JSON 解析失败。 */
"invalid_json" | 
/**  出现未声明字段（serde `deny_unknown_fields`）。 */
"unknown_field" | 
/**  缺少必填字段。 */
"missing_field" | 
/**  字段类型错误。 */
"invalid_type" | 
/**  字段取值非法（含数值越界）。 */
"invalid_value" | 
/**  枚举值不在白名单内。 */
"invalid_enum" | 
/**  超出长度上限（消息 1MiB / 标题 256 字符 / 分页 500 条等）。 */
"too_large" | 
/**  数值超出允许区间。 */
"out_of_range" | 
/**  格式非法（ULID、标识符、控制字符等）。 */
"invalid_format" | 
/**  路径校验失败（canonicalize / 白名单 / Windows 特殊路径）。 */
"path_rejected" | 
/**  启动门阻断（M1-06/A4：数据目录检测未通过，或启动自检未完成）。 */
"startup_blocked" | 
/**  数据目录迁移失败（复制/校验/原子替换/指针锁定，M1-06）。 */
"migration_failed" | 
/**  内部错误（序列化/任务调度失败等不可达路径；M1-06 启动门与迁移接线）。 */
"internal" | 
/**
 *  核心后端尚未就绪（ADR-007 增量 2）：Builder 阶段以延迟后端管理状态，
 *  `setup`（单实例插件之后）完成存储/管线注入前的过渡窗口可达。
 */
"core_not_ready" | 
/**  命令尚未实现（框架就绪，实现随对应里程碑落地）。 */
"not_implemented" | 
/**
 *  补读缺口过大（D4：>10k 拒绝自动补发；与核心管线 `readback_gap_too_large`
 *  同码透传，M3-02 属主承接项，实施计划 v1.15）。
 */
"readback_gap_too_large";

/**  IPC 命令错误的线上形态：`{ "code": "...", "message": "...", "field": "..." }`。 */
export type IpcError_Deserialize = {
	code: IpcErrorCode,
	message: string,
	field: string | null,
};

/**  IPC 命令错误的线上形态：`{ "code": "...", "message": "...", "field": "..." }`。 */
export type IpcError_Serialize = {
	code: IpcErrorCode,
	message: string,
	field?: string | null,
};

export type MessagesPageRequest = {
	session_id: string,
	last_seq?: number | null,
	limit?: number | null,
};

/**  权限决议（D9：`once` / `session` 授权；`deny` 拒绝）。 */
export type PermissionDecision = "once" | "session" | "deny";

export type PermissionResolveRequest = {
	request_id: string,
	decision: PermissionDecision,
};

export type PermissionsPendingRequest = {
	session_id?: string | null,
};

/**  `run_retry`（ADR-004）：仅终态 run 可重试；格式层校验 ULID，终态由后端判定。 */
export type RunRetryRequest = {
	run_id: string,
};

/**
 *  `runtime_enable`（ADR-004/M1-10）：仅 `disabled` 可用；
 *  `untrusted` / `version_mismatch` 必须先修复后再启用（后端状态判定）。
 */
export type RuntimeEnableRequest = {
	runtime_id: string,
};

/**
 *  `runtime_retry`（ADR-004/M1-10）：仅 `disabled + start_failed` 可用；
 *  `runtime_id` 必须命中 `runtimes` 白名单（存在性由后端判定）。
 */
export type RuntimeRetryRequest = {
	runtime_id: string,
};

export type SessionCreateRequest = {
	runtime_id: string,
	title: string,
	workspace_id?: string | null,
	model?: string | null,
};

export type SessionIdRequest = {
	session_id: string,
};

export type SessionListRequest = {
	runtime_id?: string | null,
	status?: SessionStatus | null,
	limit?: number | null,
};

export type SessionSendRequest = {
	session_id: string,
	text: string,
	/**
	 *  幂等键（ADR-005）：必填 ULID；重复发送同一 `(session_id, client_msg_id)`
	 *  返回既有 message_id/run_id，核心重启后重放同样不重复。
	 */
	client_msg_id: string,
};

/**  会话状态过滤（与附录 C `sessions.status` CHECK 枚举一一对应）。 */
export type SessionStatus = "creating" | "idle" | "running" | "paused" | "waiting_permission" | "completed" | "failed" | "cancelled";

export type SettingsGetRequest = {
	key: string,
};

export type SettingsSetRequest = {
	key: string,
	value: unknown,
};

/**  `startup_get`（ADR-006）：无参数命令；缺省载荷等价空对象，任何成员都会被严格模式拒绝。 */
export type StartupGetRequest = Record<string, never>;

/**
 *  `startup_migrate`（M1-06/A4）：迁移目标目录。
 * 
 *  形态校验（绝对路径、存在目录、Windows 特殊路径）在命令内完成；目标自身的 A4
 *  同步盘复核在启动门迁移流内执行（同一检测上下文）。
 */
export type StartupMigrateRequest = {
	target_dir: string,
};

/**  `startup_pick_target`（ADR-006）：无参数命令；缺省载荷等价空对象，任何成员都会被严格模式拒绝。 */
export type StartupPickTargetRequest = Record<string, never>;

/**
 *  `workspace_set`（ADR-004/D14）：`workspace_id` 存在性 或 `root_path`
 *  canonicalize（目录须存在；命中同步盘拒绝清单则拒绝）。P0 仅对新会话生效。
 */
export type WorkspaceSetRequest = {
	workspace_id?: string | null,
	root_path?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

